import os
def find_prj_root(path=os.getcwd()):
    if os.path.isfile(os.path.join(path,".PRJ_ROOT")):
        return path
    else:
        if path:
            return find_prj_root(os.path.dirname(path))
        else:
            raise Exception("Can not find the PRJ_ROOT directory")

PRJ_ROOT=find_prj_root()
ROOT = os.path.dirname(PRJ_ROOT)
SRC_DIR=PRJ_ROOT+'/local/src'
BIN_DIR=PRJ_ROOT+'/local/bin'

SRA_DIR="/home/mmontemurro/ncbi/public/sra/"
TMP="/scratch/tmp/"

SAMPLES=["1_NT_WH"]

SRA_AC2=["SRR8117275", "SRR8117279", "SRR8117276", "SRR8117282"]

REFERENCE="/home/bioeda/bio/spatial/refdata-GRCh38-1.0.0"
GENOME="GrCh38"
BINNING="fixed_2000000"
